POST {{host}}/signin
Content-Type: application/json

{
    "password": "password"
}

###

POST {{host}}/signup
Content-Type: application/json

{
    "email": "aa@bb.com",
    "password": "password",
    "name": "user1"
}

###
