GET {{host}}/movies
Content-Type: application/json
Authorization: {{user1_token}}

###

POST {{host}}/movies
Content-Type: application/json
Authorization: {{user1_token}}

{
  "country": "country",
  "director": "director",
  "duration": 100,
  "year": "2020",
  "description": "description",
  "image": "https://image",
  "trailerLink": "https://trailerLink",
  "thumbnail": "https://thumbnail",
  "owner": "635e71c809a5478ee3b4221d",
  "movieId": 1,
  "nameRU": "nameRU",
  "nameEN": "nameEN"
}

###

DELETE {{host}}/movies/{{movie1_id}}
Content-Type: application/json
Authorization: {{user2_token}}

###
