GET {{host}}/users/me
Content-Type: application/json
Authorization: {{user1_token}}

###

PATCH {{host}}/users/me
Content-Type: application/json
Authorization: {{user1_token}}

{
    "email": "a@b.c",
    "name": "Меместо"
}

###
